CREATE TABLE IF NOT EXISTS BOOK
(
    ID                  BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE               VARCHAR(50) NOT NULL,
    AUTHOR_ID           BIGINT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);