INSERT INTO BOOK VALUES (null, 'Title1', 1);
INSERT INTO BOOK VALUES (null, 'Title1', 3);
INSERT INTO BOOK VALUES (null, 'Title1', 4);
INSERT INTO BOOK VALUES (null, 'Title2', 2);
INSERT INTO BOOK VALUES (null, 'Title3', 3);
INSERT INTO BOOK VALUES (null, 'Title4', 2);
INSERT INTO BOOK VALUES (null, 'Title4', 4);
INSERT INTO BOOK VALUES (null, 'Title5', 5);